# api redirect.
[[redirects]]
  from = "/api/*"
  to = "http://ec2-3-110-207-150.ap-south-1.compute.amazonaws.com/:splat"
  status = 200
# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200